import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateDrizzleJson, generateMigration } from 'drizzle-kit/api';
import { knowledgeSchema } from '../src/database/knowledge/schema';

export const knowledgeSchemaSqlPath = fileURLToPath(new URL('../src/database/knowledge/current.sql', import.meta.url));

/** Empty → current schema only. There is no version chain or legacy adapter. */
export async function generateKnowledgeSchemaSql(): Promise<string> {
  const empty = generateDrizzleJson({});
  const current = generateDrizzleJson(knowledgeSchema, undefined, ['knowledge', 'knowledge_auth']);
  const statements = await generateMigration(empty, current);
  return [
    '-- Generated by backend/scripts/knowledge-schema.ts from Drizzle schema. Do not edit.',
    '-- Current initialization only; tenant RLS is installed by D02.',
    'CREATE EXTENSION IF NOT EXISTS ltree;',
    'CREATE EXTENSION IF NOT EXISTS vector;',
    'CREATE EXTENSION IF NOT EXISTS pg_search;',
    ...statements,
    '',
  ].join('\n');
}

async function main() {
  const sql = await generateKnowledgeSchemaSql();
  const command = process.argv[2] ?? '--check';
  if (command === '--write') {
    await writeFile(knowledgeSchemaSqlPath, sql, 'utf8');
    console.log(`Generated current schema: ${knowledgeSchemaSqlPath}`);
  } else if (command === '--sql') {
    process.stdout.write(sql);
  } else if (command === '--check') {
    const saved = await readFile(knowledgeSchemaSqlPath, 'utf8');
    if (saved.replaceAll('\r\n', '\n') !== sql) throw new Error('Current SQL has drifted. Run bun backend/scripts/knowledge-schema.ts --write.');
    console.log('Knowledge current SQL matches the Drizzle source.');
  } else {
    throw new Error('Usage: bun backend/scripts/knowledge-schema.ts [--check|--write|--sql]');
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
