-- Generated by backend/scripts/knowledge-schema.ts from Drizzle schema. Do not edit.
-- Current initialization only; tenant RLS is installed by D02.
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_search;
CREATE SCHEMA "knowledge_auth";

CREATE SCHEMA "knowledge";

CREATE TYPE "knowledge"."ai_task_kind" AS ENUM('inline', 'continue', 'chat', 'aiBlock', 'organize', 'report', 'mcp');
CREATE TYPE "knowledge"."ai_task_status" AS ENUM('running', 'awaiting_approval', 'done', 'failed');
CREATE TYPE "knowledge"."comment_thread_status" AS ENUM('open', 'resolved');
CREATE TYPE "knowledge"."member_role" AS ENUM('owner', 'admin', 'member', 'guest');
CREATE TYPE "knowledge"."model_tier" AS ENUM('fast', 'smart', 'embed', 'rerank', 'vision');
CREATE TYPE "knowledge"."outbox_topic" AS ENUM('doc.changed', 'acl.changed', 'asset.created', 'workspace.event');
CREATE TYPE "knowledge"."page_kind" AS ENUM('doc', 'database', 'row');
CREATE TYPE "knowledge"."permission_level" AS ENUM('view', 'comment', 'edit', 'full');
CREATE TYPE "knowledge"."workspace_kind" AS ENUM('personal', 'team');
CREATE TABLE "knowledge"."ai_task" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"initiated_by" uuid NOT NULL,
	"kind" "knowledge"."ai_task_kind" NOT NULL,
	"status" "knowledge"."ai_task_status" DEFAULT 'running' NOT NULL,
	"state" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ai_task_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "ai_task_state_object" CHECK (jsonb_typeof("knowledge"."ai_task"."state") = 'object')
);

CREATE TABLE "knowledge"."ai_usage" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"task_id" uuid,
	"tier" "knowledge"."model_tier" NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"duration_ms" bigint NOT NULL,
	"trace_id" varchar(32),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ai_usage_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "ai_usage_nonnegative" CHECK ("knowledge"."ai_usage"."input_tokens" >= 0 AND "knowledge"."ai_usage"."output_tokens" >= 0 AND "knowledge"."ai_usage"."duration_ms" >= 0)
);

CREATE TABLE "knowledge"."asset" (
	"workspace_id" uuid NOT NULL,
	"hash" varchar(64) NOT NULL,
	"mime" varchar(200) NOT NULL,
	"size" bigint NOT NULL,
	"meta" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"derived" jsonb DEFAULT '{"status":"pending"}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "asset_workspace_id_hash_pk" PRIMARY KEY("workspace_id","hash"),
	CONSTRAINT "asset_hash_valid" CHECK ("knowledge"."asset"."hash" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "asset_size_nonnegative" CHECK ("knowledge"."asset"."size" >= 0),
	CONSTRAINT "asset_mime_valid" CHECK ("knowledge"."asset"."mime" ~ '^[A-Za-z0-9_.+-]+/[A-Za-z0-9_.+-]+$'),
	CONSTRAINT "asset_meta_object" CHECK (jsonb_typeof("knowledge"."asset"."meta") = 'object'),
	CONSTRAINT "asset_derived_object" CHECK (jsonb_typeof("knowledge"."asset"."derived") = 'object' AND "knowledge"."asset"."derived"->>'status' IS NOT NULL AND "knowledge"."asset"."derived"->>'status' IN ('pending', 'processing', 'ready', 'failed'))
);

CREATE TABLE "knowledge_auth"."account" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_provider_account_unique" UNIQUE("provider_id","account_id")
);

CREATE TABLE "knowledge_auth"."session" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);

CREATE TABLE "knowledge_auth"."user" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_name_not_empty" CHECK (length(btrim("knowledge_auth"."user"."name")) > 0)
);

CREATE TABLE "knowledge_auth"."verification" (
	"id" uuid PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "knowledge"."backlink" (
	"workspace_id" uuid NOT NULL,
	"src_page_id" uuid NOT NULL,
	"src_block_id" varchar(128) NOT NULL,
	"dst_page_id" uuid NOT NULL,
	"dst_block_id" varchar(128),
	CONSTRAINT "backlink_source_target_unique" UNIQUE NULLS NOT DISTINCT("workspace_id","src_page_id","src_block_id","dst_page_id","dst_block_id"),
	CONSTRAINT "backlink_source_block_valid" CHECK ("knowledge"."backlink"."src_block_id" ~ '^[A-Za-z0-9_-]+$'),
	CONSTRAINT "backlink_destination_block_valid" CHECK ("knowledge"."backlink"."dst_block_id" IS NULL OR "knowledge"."backlink"."dst_block_id" ~ '^[A-Za-z0-9_-]+$')
);

CREATE TABLE "knowledge"."block_embedding_staging" (
	"workspace_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"block_id" varchar(128) NOT NULL,
	"embed_model" text NOT NULL,
	"embed_dimensions" integer NOT NULL,
	"content_hash" varchar(64) NOT NULL,
	"embedding" vector NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "block_embedding_staging_pk" PRIMARY KEY("workspace_id","page_id","block_id","embed_model","embed_dimensions"),
	CONSTRAINT "block_embedding_staging_hash_valid" CHECK ("knowledge"."block_embedding_staging"."content_hash" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "block_embedding_staging_metadata" CHECK (length("knowledge"."block_embedding_staging"."embed_model") > 0 AND "knowledge"."block_embedding_staging"."embed_dimensions" > 0 AND vector_dims("knowledge"."block_embedding_staging"."embedding") = "knowledge"."block_embedding_staging"."embed_dimensions")
);

CREATE TABLE "knowledge"."block_index" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "knowledge"."block_index_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"workspace_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"block_id" varchar(128) NOT NULL,
	"block_type" varchar(60) NOT NULL,
	"content_md" text NOT NULL,
	"content_hash" varchar(64) NOT NULL,
	"embedding" vector,
	"embed_model" text,
	"embed_dimensions" integer,
	"principals" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"acl_revision" bigint DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "block_index_workspace_page_block_unique" UNIQUE("workspace_id","page_id","block_id"),
	CONSTRAINT "block_index_block_id_valid" CHECK ("knowledge"."block_index"."block_id" ~ '^[A-Za-z0-9_-]+$'),
	CONSTRAINT "block_index_content_hash_valid" CHECK ("knowledge"."block_index"."content_hash" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "block_index_embedding_metadata" CHECK (("knowledge"."block_index"."embedding" IS NULL AND "knowledge"."block_index"."embed_model" IS NULL AND "knowledge"."block_index"."embed_dimensions" IS NULL) OR ("knowledge"."block_index"."embedding" IS NOT NULL AND "knowledge"."block_index"."embed_model" IS NOT NULL AND length("knowledge"."block_index"."embed_model") > 0 AND "knowledge"."block_index"."embed_dimensions" IS NOT NULL AND "knowledge"."block_index"."embed_dimensions" > 0 AND vector_dims("knowledge"."block_index"."embedding") = "knowledge"."block_index"."embed_dimensions")),
	CONSTRAINT "block_index_acl_revision_nonnegative" CHECK ("knowledge"."block_index"."acl_revision" >= 0)
);

CREATE TABLE "knowledge"."comment" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"thread_id" uuid NOT NULL,
	"author_id" uuid NOT NULL,
	"body_md" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "comment_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "comment_body_valid" CHECK (length(btrim("knowledge"."comment"."body_md")) BETWEEN 1 AND 50000)
);

CREATE TABLE "knowledge"."comment_thread" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"status" "knowledge"."comment_thread_status" DEFAULT 'open' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "comment_thread_workspace_id_id_pk" PRIMARY KEY("workspace_id","id")
);

CREATE TABLE "knowledge"."database_definition" (
	"workspace_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"teamspace_id" uuid NOT NULL,
	"page_kind" "knowledge"."page_kind" DEFAULT 'database' NOT NULL,
	"properties" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "database_definition_workspace_id_page_id_pk" PRIMARY KEY("workspace_id","page_id"),
	CONSTRAINT "database_definition_teamspace_page_unique" UNIQUE("workspace_id","teamspace_id","page_id"),
	CONSTRAINT "database_definition_database_kind" CHECK ("knowledge"."database_definition"."page_kind" = 'database'),
	CONSTRAINT "database_definition_properties_array" CHECK (jsonb_typeof("knowledge"."database_definition"."properties") = 'array' AND jsonb_array_length("knowledge"."database_definition"."properties") <= 100)
);

CREATE TABLE "knowledge"."doc_checkpoint" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"state" "bytea" NOT NULL,
	"state_vector" "bytea" NOT NULL,
	"authors" uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
	"label" varchar(200),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doc_checkpoint_workspace_id_id_pk" PRIMARY KEY("workspace_id","id")
);

CREATE TABLE "knowledge"."doc_state" (
	"workspace_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"state" "bytea" NOT NULL,
	"state_vector" "bytea" NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doc_state_workspace_id_page_id_pk" PRIMARY KEY("workspace_id","page_id")
);

CREATE TABLE "knowledge"."group" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"name" varchar(120) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "group_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "group_workspace_name_unique" UNIQUE("workspace_id","name"),
	CONSTRAINT "group_name_not_empty" CHECK (length(btrim("knowledge"."group"."name")) > 0)
);

CREATE TABLE "knowledge"."group_member" (
	"workspace_id" uuid NOT NULL,
	"group_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "group_member_workspace_id_group_id_user_id_pk" PRIMARY KEY("workspace_id","group_id","user_id")
);

CREATE TABLE "knowledge"."member" (
	"workspace_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "knowledge"."member_role" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "member_workspace_id_user_id_pk" PRIMARY KEY("workspace_id","user_id")
);

CREATE TABLE "knowledge"."model_credential" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" varchar(80) NOT NULL,
	"encrypted_secret" "bytea" NOT NULL,
	"endpoint" text,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "model_credential_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "model_credential_secret_not_empty" CHECK (octet_length("knowledge"."model_credential"."encrypted_secret") > 0)
);

CREATE TABLE "knowledge"."notification" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"page_id" uuid,
	"kind" varchar(80) NOT NULL,
	"payload" jsonb NOT NULL,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "notification_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "notification_payload_object" CHECK (jsonb_typeof("knowledge"."notification"."payload") = 'object')
);

CREATE TABLE "knowledge"."outbox" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"topic" "knowledge"."outbox_topic" NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"dispatched_at" timestamp with time zone,
	CONSTRAINT "outbox_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "outbox_payload_scope" CHECK (jsonb_typeof("knowledge"."outbox"."payload") = 'object' AND "knowledge"."outbox"."payload"->>'workspaceId' IS NOT DISTINCT FROM "knowledge"."outbox"."workspace_id"::text AND "knowledge"."outbox"."payload"->>'topic' IS NOT DISTINCT FROM "knowledge"."outbox"."topic"::text)
);

CREATE TABLE "knowledge"."page" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"teamspace_id" uuid NOT NULL,
	"parent_id" uuid,
	"position" varchar(256) NOT NULL,
	"path" "ltree" NOT NULL,
	"kind" "knowledge"."page_kind" DEFAULT 'doc' NOT NULL,
	"database_id" uuid,
	"properties" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"title" varchar(500) DEFAULT '' NOT NULL,
	"icon" varchar(200),
	"cover" varchar(2048),
	"inherits_permissions" boolean DEFAULT true NOT NULL,
	"acl_revision" bigint DEFAULT 0 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "page_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "page_workspace_teamspace_id_unique" UNIQUE("workspace_id","teamspace_id","id"),
	CONSTRAINT "page_workspace_teamspace_id_kind_unique" UNIQUE("workspace_id","teamspace_id","id","kind"),
	CONSTRAINT "page_workspace_path_unique" UNIQUE("workspace_id","path"),
	CONSTRAINT "page_not_own_parent" CHECK ("knowledge"."page"."parent_id" IS NULL OR "knowledge"."page"."parent_id" <> "knowledge"."page"."id"),
	CONSTRAINT "page_row_database_relation" CHECK (("knowledge"."page"."kind" = 'row') = ("knowledge"."page"."database_id" IS NOT NULL)),
	CONSTRAINT "page_not_own_database" CHECK ("knowledge"."page"."database_id" IS NULL OR "knowledge"."page"."database_id" <> "knowledge"."page"."id"),
	CONSTRAINT "page_position_valid" CHECK ("knowledge"."page"."position" ~ '^[A-Za-z0-9]+$'),
	CONSTRAINT "page_path_valid" CHECK (nlevel("knowledge"."page"."path") > 0 AND subpath("knowledge"."page"."path", -1)::text = replace("knowledge"."page"."id"::text, '-', '_')),
	CONSTRAINT "page_root_path_depth" CHECK (("knowledge"."page"."parent_id" IS NULL) = (nlevel("knowledge"."page"."path") = 1)),
	CONSTRAINT "page_properties_object" CHECK (jsonb_typeof("knowledge"."page"."properties") = 'object'),
	CONSTRAINT "page_acl_revision_nonnegative" CHECK ("knowledge"."page"."acl_revision" >= 0)
);

CREATE TABLE "knowledge"."page_acl" (
	"workspace_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"principal" text NOT NULL,
	"level" "knowledge"."permission_level" NOT NULL,
	"inherited" boolean DEFAULT false NOT NULL,
	CONSTRAINT "page_acl_workspace_id_page_id_principal_pk" PRIMARY KEY("workspace_id","page_id","principal"),
	CONSTRAINT "page_acl_principal_valid" CHECK ("knowledge"."page_acl"."principal" ~ '^(user|group|workspace|link):[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')
);

CREATE TABLE "knowledge"."page_effective_acl" (
	"workspace_id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"view_principals" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"comment_principals" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"edit_principals" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"full_principals" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"revision" bigint DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "page_effective_acl_workspace_id_page_id_pk" PRIMARY KEY("workspace_id","page_id"),
	CONSTRAINT "page_effective_acl_level_hierarchy" CHECK ("knowledge"."page_effective_acl"."view_principals" @> "knowledge"."page_effective_acl"."comment_principals" AND "knowledge"."page_effective_acl"."comment_principals" @> "knowledge"."page_effective_acl"."edit_principals" AND "knowledge"."page_effective_acl"."edit_principals" @> "knowledge"."page_effective_acl"."full_principals"),
	CONSTRAINT "page_effective_acl_revision_nonnegative" CHECK ("knowledge"."page_effective_acl"."revision" >= 0)
);

CREATE TABLE "knowledge"."personal_access_token" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"name" varchar(120) NOT NULL,
	"token_hash" varchar(64) NOT NULL,
	"scopes" text[] NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"last_used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "personal_access_token_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "personal_access_token_hash_valid" CHECK ("knowledge"."personal_access_token"."token_hash" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "personal_access_token_scopes_nonempty" CHECK (cardinality("knowledge"."personal_access_token"."scopes") > 0)
);

CREATE TABLE "knowledge"."share_link" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"page_id" uuid NOT NULL,
	"token_hash" varchar(64) NOT NULL,
	"level" "knowledge"."permission_level" DEFAULT 'view' NOT NULL,
	"created_by" uuid NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "share_link_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "share_link_token_hash_valid" CHECK ("knowledge"."share_link"."token_hash" ~ '^[a-f0-9]{64}$')
);

CREATE TABLE "knowledge"."teamspace" (
	"workspace_id" uuid NOT NULL,
	"id" uuid NOT NULL,
	"name" varchar(120) NOT NULL,
	"default_access" "knowledge"."permission_level",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "teamspace_workspace_id_id_pk" PRIMARY KEY("workspace_id","id"),
	CONSTRAINT "teamspace_name_not_empty" CHECK (length(btrim("knowledge"."teamspace"."name")) > 0)
);

CREATE TABLE "knowledge"."workspace" (
	"workspace_id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(120) NOT NULL,
	"kind" "knowledge"."workspace_kind" NOT NULL,
	"settings" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "workspace_name_not_empty" CHECK (length(btrim("knowledge"."workspace"."name")) > 0),
	CONSTRAINT "workspace_settings_object" CHECK (jsonb_typeof("knowledge"."workspace"."settings") = 'object')
);

ALTER TABLE "knowledge"."ai_task" ADD CONSTRAINT "ai_task_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."ai_task" ADD CONSTRAINT "ai_task_initiated_by_user_id_fk" FOREIGN KEY ("initiated_by") REFERENCES "knowledge_auth"."user"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "knowledge"."ai_usage" ADD CONSTRAINT "ai_usage_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."ai_usage" ADD CONSTRAINT "ai_usage_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "knowledge"."ai_usage" ADD CONSTRAINT "ai_usage_workspace_id_task_id_ai_task_workspace_id_id_fk" FOREIGN KEY ("workspace_id","task_id") REFERENCES "knowledge"."ai_task"("workspace_id","id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "knowledge"."asset" ADD CONSTRAINT "asset_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_auth"."account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_auth"."session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."backlink" ADD CONSTRAINT "backlink_workspace_id_src_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","src_page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."backlink" ADD CONSTRAINT "backlink_workspace_id_dst_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","dst_page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."block_embedding_staging" ADD CONSTRAINT "block_embedding_staging_block_fk" FOREIGN KEY ("workspace_id","page_id","block_id") REFERENCES "knowledge"."block_index"("workspace_id","page_id","block_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."block_index" ADD CONSTRAINT "block_index_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."comment" ADD CONSTRAINT "comment_author_id_user_id_fk" FOREIGN KEY ("author_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "knowledge"."comment" ADD CONSTRAINT "comment_thread_fk" FOREIGN KEY ("workspace_id","thread_id") REFERENCES "knowledge"."comment_thread"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."comment_thread" ADD CONSTRAINT "comment_thread_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."database_definition" ADD CONSTRAINT "database_definition_page_fk" FOREIGN KEY ("workspace_id","teamspace_id","page_id","page_kind") REFERENCES "knowledge"."page"("workspace_id","teamspace_id","id","kind") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "knowledge"."doc_checkpoint" ADD CONSTRAINT "doc_checkpoint_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."doc_state" ADD CONSTRAINT "doc_state_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."group" ADD CONSTRAINT "group_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."group_member" ADD CONSTRAINT "group_member_workspace_id_group_id_group_workspace_id_id_fk" FOREIGN KEY ("workspace_id","group_id") REFERENCES "knowledge"."group"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."group_member" ADD CONSTRAINT "group_member_membership_fk" FOREIGN KEY ("workspace_id","user_id") REFERENCES "knowledge"."member"("workspace_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."member" ADD CONSTRAINT "member_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."member" ADD CONSTRAINT "member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."model_credential" ADD CONSTRAINT "model_credential_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."model_credential" ADD CONSTRAINT "model_credential_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."notification" ADD CONSTRAINT "notification_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."notification" ADD CONSTRAINT "notification_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."notification" ADD CONSTRAINT "notification_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."outbox" ADD CONSTRAINT "outbox_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."page" ADD CONSTRAINT "page_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "knowledge_auth"."user"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "knowledge"."page" ADD CONSTRAINT "page_teamspace_fk" FOREIGN KEY ("workspace_id","teamspace_id") REFERENCES "knowledge"."teamspace"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."page" ADD CONSTRAINT "page_parent_fk" FOREIGN KEY ("workspace_id","teamspace_id","parent_id") REFERENCES "knowledge"."page"("workspace_id","teamspace_id","id") ON DELETE no action ON UPDATE cascade;
ALTER TABLE "knowledge"."page" ADD CONSTRAINT "page_database_fk" FOREIGN KEY ("workspace_id","teamspace_id","database_id") REFERENCES "knowledge"."database_definition"("workspace_id","teamspace_id","page_id") ON DELETE no action ON UPDATE cascade;
ALTER TABLE "knowledge"."page_acl" ADD CONSTRAINT "page_acl_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."page_effective_acl" ADD CONSTRAINT "page_effective_acl_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."personal_access_token" ADD CONSTRAINT "personal_access_token_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."personal_access_token" ADD CONSTRAINT "personal_access_token_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "knowledge_auth"."user"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."share_link" ADD CONSTRAINT "share_link_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "knowledge_auth"."user"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "knowledge"."share_link" ADD CONSTRAINT "share_link_workspace_id_page_id_page_workspace_id_id_fk" FOREIGN KEY ("workspace_id","page_id") REFERENCES "knowledge"."page"("workspace_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge"."teamspace" ADD CONSTRAINT "teamspace_workspace_id_workspace_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "knowledge"."workspace"("workspace_id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "ai_task_workspace_status_idx" ON "knowledge"."ai_task" USING btree ("workspace_id","status","updated_at");
CREATE INDEX "ai_task_initiator_idx" ON "knowledge"."ai_task" USING btree ("initiated_by");
CREATE INDEX "ai_usage_workspace_time_idx" ON "knowledge"."ai_usage" USING btree ("workspace_id","created_at");
CREATE INDEX "ai_usage_task_idx" ON "knowledge"."ai_usage" USING btree ("workspace_id","task_id");
CREATE INDEX "ai_usage_user_idx" ON "knowledge"."ai_usage" USING btree ("user_id");
CREATE INDEX "account_user_idx" ON "knowledge_auth"."account" USING btree ("user_id");
CREATE INDEX "session_user_idx" ON "knowledge_auth"."session" USING btree ("user_id");
CREATE INDEX "session_expiry_idx" ON "knowledge_auth"."session" USING btree ("expires_at");
CREATE INDEX "verification_identifier_idx" ON "knowledge_auth"."verification" USING btree ("identifier");
CREATE INDEX "verification_expiry_idx" ON "knowledge_auth"."verification" USING btree ("expires_at");
CREATE INDEX "backlink_destination_idx" ON "knowledge"."backlink" USING btree ("workspace_id","dst_page_id","dst_block_id");
CREATE INDEX "block_embedding_staging_model_idx" ON "knowledge"."block_embedding_staging" USING btree ("workspace_id","embed_model","embed_dimensions");
CREATE INDEX "block_index_principals_gin_idx" ON "knowledge"."block_index" USING gin ("principals");
CREATE INDEX "block_index_embedding_model_idx" ON "knowledge"."block_index" USING btree ("workspace_id","embed_model","embed_dimensions");
CREATE INDEX "comment_thread_time_idx" ON "knowledge"."comment" USING btree ("workspace_id","thread_id","created_at");
CREATE INDEX "comment_author_idx" ON "knowledge"."comment" USING btree ("author_id");
CREATE INDEX "comment_thread_page_idx" ON "knowledge"."comment_thread" USING btree ("workspace_id","page_id","status");
CREATE INDEX "doc_checkpoint_page_time_idx" ON "knowledge"."doc_checkpoint" USING btree ("workspace_id","page_id","created_at");
CREATE INDEX "group_member_user_idx" ON "knowledge"."group_member" USING btree ("workspace_id","user_id");
CREATE INDEX "member_user_idx" ON "knowledge"."member" USING btree ("user_id","workspace_id");
CREATE INDEX "model_credential_user_idx" ON "knowledge"."model_credential" USING btree ("user_id");
CREATE INDEX "notification_user_time_idx" ON "knowledge"."notification" USING btree ("workspace_id","user_id","created_at");
CREATE INDEX "notification_user_idx" ON "knowledge"."notification" USING btree ("user_id");
CREATE INDEX "notification_page_idx" ON "knowledge"."notification" USING btree ("workspace_id","page_id");
CREATE INDEX "outbox_pending_idx" ON "knowledge"."outbox" USING btree ("created_at","workspace_id","id") WHERE "knowledge"."outbox"."dispatched_at" IS NULL;
CREATE INDEX "page_tree_idx" ON "knowledge"."page" USING btree ("workspace_id","teamspace_id","parent_id","position") WHERE "knowledge"."page"."deleted_at" IS NULL;
CREATE INDEX "page_parent_idx" ON "knowledge"."page" USING btree ("workspace_id","teamspace_id","parent_id");
CREATE INDEX "page_database_idx" ON "knowledge"."page" USING btree ("workspace_id","teamspace_id","database_id");
CREATE INDEX "page_path_gist_idx" ON "knowledge"."page" USING gist ("path");
CREATE INDEX "page_created_by_idx" ON "knowledge"."page" USING btree ("created_by");
CREATE INDEX "page_acl_principal_idx" ON "knowledge"."page_acl" USING btree ("workspace_id","principal");
CREATE INDEX "page_effective_acl_view_gin_idx" ON "knowledge"."page_effective_acl" USING gin ("view_principals");
CREATE INDEX "page_effective_acl_comment_gin_idx" ON "knowledge"."page_effective_acl" USING gin ("comment_principals");
CREATE INDEX "page_effective_acl_edit_gin_idx" ON "knowledge"."page_effective_acl" USING gin ("edit_principals");
CREATE INDEX "page_effective_acl_full_gin_idx" ON "knowledge"."page_effective_acl" USING gin ("full_principals");
CREATE INDEX "personal_access_token_hash_idx" ON "knowledge"."personal_access_token" USING btree ("workspace_id","token_hash");
CREATE INDEX "personal_access_token_user_idx" ON "knowledge"."personal_access_token" USING btree ("user_id");
CREATE INDEX "share_link_page_idx" ON "knowledge"."share_link" USING btree ("workspace_id","page_id");
CREATE INDEX "share_link_token_idx" ON "knowledge"."share_link" USING btree ("workspace_id","token_hash");
CREATE INDEX "share_link_created_by_idx" ON "knowledge"."share_link" USING btree ("created_by");
