export { createKnowledgeAuth } from './service';
export type { KnowledgeAuth, AuthDiagnostic } from './service';
export { createKnowledgeAuthRoutes } from './http';
export { getKnowledgeIdentity, requireKnowledgeIdentity } from './identity';
export type { KnowledgeIdentity } from './identity';
export { readKnowledgeAuthConfig, validateKnowledgeAuthConfig, knowledgeAuthBasePath } from './config';
export type { KnowledgeAuthConfig } from './config';
export { createSmtpAuthEmailTransport } from './email';
export type { AuthEmailTransport } from './email';
export { createKnowledgeTokenService } from './tokens';
export type { KnowledgeTokenSummary } from './tokens';
export { createKnowledgeRequestAuthenticator, requireKnowledgeRequest, requireKnowledgeScopes } from './request-context';
export type { KnowledgeRequestContext, KnowledgeRequestAuthenticator } from './request-context';
export { KnowledgeAccessError, knowledgeAccessErrorResponse, knowledgeTokenScopes, createKnowledgeTokenInputSchema, revokeKnowledgeTokenInputSchema } from './access-policy';
export type { KnowledgeTokenScope, KnowledgeAccessErrorCode, KnowledgeAccessDiagnostic } from './access-policy';
export type { KnowledgeAccessDependencies } from './session-access';
